name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/bnlnpps/xpload-build
