name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Django App
        uses: actions/checkout@v2
        with:
          repository: plexoos/npdb
          ref: develop
          path: npdb

      - name: Start Django App
        run: docker-compose -f npdb/docker-compose.yml up -d --build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/bnlnpps/xpload-build
          target: build-stage
          load: true

      - name: Run Tests
        run: |
             docker run --rm --network=host -e XPLOAD_CONFIG_NAME=dev ghcr.io/bnlnpps/xpload-build xpload/example/db_init_sphenix.sh
             docker run --network=host ghcr.io/bnlnpps/xpload-build ctest --test-dir build -V
