name: CI Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        compiler: [gcc8, gcc10, clang12]
        prereq: [ {python: 3.8.0, cmake: 3.20.6, curl: 7.79.1}, {python: 3.10.4, cmake: 3.23.1, curl: 7.79.1} ]
    env:
      BUILD_LABEL: ${{ matrix.compiler }}-python${{ matrix.prereq.python }}-cmake${{ matrix.prereq.cmake }}-curl${{ matrix.prereq.curl }}
    steps:
      - name: Check out Django App
        uses: actions/checkout@v2
        with:
          repository: plexoos/npdb
          ref: develop
          path: npdb

      - name: Start Django App
        run: docker-compose -f npdb/docker-compose.yml up -d --build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Cache base-stage
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/bnlnpps/xpload-build:cache-${{ env.BUILD_LABEL }}
          cache-to:   type=registry,ref=ghcr.io/bnlnpps/xpload-build:cache-${{ env.BUILD_LABEL }},mode=max
          target: base-stage
          build-args: |
            compiler=${{ matrix.compiler }}
            python=${{ matrix.prereq.python }}

      - name: Build and Load build-stage
        uses: docker/build-push-action@v2
        with:
          cache-from: type=registry,ref=ghcr.io/bnlnpps/xpload-build:cache-${{ env.BUILD_LABEL }}
          tags: ghcr.io/bnlnpps/xpload-build
          load: true
          target: build-stage
          build-args: |
            compiler=${{ matrix.compiler }}
            python=${{ matrix.prereq.python }}

      - name: Run xpload pytests
        run: docker run --rm --network=host -e XPLOAD_CONFIG=dev ghcr.io/bnlnpps/xpload-build pytest xpload/tools/

      - name: Run CLI Tests
        run: docker run --rm --network=host -e XPLOAD_CONFIG=dev -v /tmp:/tmp ghcr.io/bnlnpps/xpload-build xpload/test/test_cli.sh

      - name: Run Library Tests
        run: docker run --rm --network=host -e XPLOAD_CONFIG=dev -v /tmp:/tmp ghcr.io/bnlnpps/xpload-build ctest --test-dir build -V
