name: CI Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./xpload
    steps:
      - name: Check out Django App
        uses: actions/checkout@v2
        with:
          repository: plexoos/npdb
          ref: develop
          path: npdb

      - name: Start Django App
        working-directory: ./npdb
        run: docker-compose -f docker-compose.yml up -d --build

      - name: Check out xpload
        uses: actions/checkout@v2
        with:
          path: xpload

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Python Environment
        run: |
          python3 -m venv venv
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test xpload
        run: |
          source venv/bin/activate
          ./tools/xpload.py -c dev push tag1 domain1 payload1
          ./tools/xpload.py -c dev push tag2 domain2 payload2
          ./tools/xpload.py -c dev push tag3 domain3 payload3
          ./tools/xpload.py -c dev show payloads
          ./tools/xpload.py -c dev show domains
          ./tools/xpload.py -c dev show tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/bnlnpps/xpload-build
          target: build-stage
          load: true

      - name: Run Tests
        run: docker run --network=host ghcr.io/bnlnpps/xpload-build /bin/bash -c "ctest --test-dir build -VV"
