name: CI Build

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Django App
        uses: actions/checkout@v2
        with:
          repository: plexoos/npdb
          ref: develop
          path: npdb

      - name: Start Django App
        run: docker-compose -f npdb/docker-compose.yml up -d --build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push with Docker
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/bnlnpps/xpload-build
          target: build-stage
          push: true

      - name: Run CLI Tests
        run: docker run --rm --network=host -e XPLOAD_CONFIG=dev ghcr.io/bnlnpps/xpload-build xpload/test/test_cli.sh

      - name: Run Library Tests
        run: docker run --rm --network=host -e XPLOAD_CONFIG=dev ghcr.io/bnlnpps/xpload-build ctest --test-dir build -V
